export const portfolios = [
  {
    id: 1,
    heading: 'Twigsee',
    content: 'School management mobile & web app',
    image: '/assets/images/portfolio/Twigsee0.png',
    images: [
      '/assets/images/portfolio/Twigsee1.png',
      '/assets/images/portfolio/Twigsee2.png',
      '/assets/images/portfolio/Twigsee3.png',
    ],
    description: [
      'Twigsee is a comprehensive digital solution designed to streamline and enhance the efficiency of educational institutions.',
      'This user-friendly platform enables administrators to effortlessly manage student records, attendance, and academic performance.',
      'Teachers can utilize the app to communicate with parents, assign homework, and track student progress.',
      "Parents can stay informed about their child's school activities, grades, and upcoming events through a dedicated portal.",
      'Additionally, the app offers a secure and convenient way to handle administrative tasks such as fee payments and school announcements, fostering better communication and organization within the school community.',
    ],
    category: 'Web Development',
    client: 'Twigsee s.r.o.',
    date: 'March, 2020',
    url: 'https://www.twigsee.com',
  },
  {
    id: 2,
    heading: 'Kwik',
    content: 'Fast delivery management app',
    image: '/assets/images/portfolio/Kwik0.png',
    images: [
      '/assets/images/portfolio/Kwik1.png',
      '/assets/images/portfolio/Kwik2.png',
      '/assets/images/portfolio/Kwik3.png',
    ],
    description: [
      'Kwik Delivery is a cutting-edge solution designed to optimize and streamline the entire delivery process.',
      'This user-friendly platform allows businesses to efficiently plan routes, assign deliveries, and track the status of shipments in real-time.',
      'Delivery drivers can access the app to receive orders, navigate routes, and update order statuses, ensuring a seamless and on-time delivery experience.',
      "Customers benefit from the app's transparency, enabling them to track their orders, receive notifications, and provide feedback.",
      'With robust analytics and reporting features, businesses can make data-driven decisions to enhance their delivery operations and customer satisfaction levels.',
    ],
    category: 'Web Development',
    client: 'Kwik Delivery',
    date: 'July, 2021',
    url: 'https://kwik.delivery',
  },
  {
    id: 3,
    heading: 'Goldwise',
    content: 'Finance dashboard application',
    image: '/assets/images/portfolio/Goldwise0.png',
    images: [
      '/assets/images/portfolio/Goldwise1.png',
      '/assets/images/portfolio/Goldwise2.png',
      '/assets/images/portfolio/Goldwise3.png',
    ],
    description: [
      'Goldwise project is aimed at creating an advanced financial management tool that provides users with a holistic view of their financial data.',
      'This user-friendly web-based dashboard will integrate seamlessly with various financial accounts, including bank accounts, credit cards, investments, and more.',
      'Users will be able to track their income, expenses, and investments in real-time, empowering them to make informed financial decisions.',
      'The dashboard will feature interactive charts and graphs for visualizing financial trends and setting personalized financial goals.',
      "Robust security measures will ensure the privacy and protection of users' sensitive financial information, making this dashboard a trusted and invaluable resource for managing their finances effectively.",
    ],
    category: 'Web Development',
    client: 'MiYuMi AI',
    date: 'February, 2022',
    url: 'https://goldwise.com',
  },
  {
    id: 4,
    heading: 'Autohaus',
    content: 'Car sell & rent dealership platform',
    image: '/assets/images/portfolio/Autohaus0.png',
    images: [
      '/assets/images/portfolio/Autohaus1.png',
      '/assets/images/portfolio/Autohaus2.png',
      '/assets/images/portfolio/Autohaus3.png',
    ],
    description: [
      'Autohaus is a comprehensive online marketplace designed to connect buyers, sellers, and renters in the automotive industry.',
      'This robust platform allows individuals and dealerships to list their vehicles for sale or rent, complete with detailed descriptions, high-quality images, and pricing information.',
      'Buyers and renters can easily browse a wide range of vehicles, apply filters, and compare options to find the perfect car for their needs.',
      'The platform also offers secure payment processing, document management, and scheduling features to facilitate seamless transactions.',
      'With a user-friendly interface and advanced search capabilities, our platform aims to simplify and enhance the car buying and renting experience for both consumers and automotive businesses.',
    ],
    category: 'Web Development',
    client: 'Autohaus GmbH',
    date: 'October, 2022',
    url: 'https://www.autohaus-melzer.de',
  },
  // {
  //   id: 5,
  //   heading: 'App 2',
  //   content: 'Lorem ipsum, dolor sit amet consectetur',
  //   image: '/assets/images/portfolio/app-2.jpg',
  // },
  // {
  //   id: 6,
  //   heading: 'Product 2',
  //   content: 'Lorem ipsum, dolor sit amet consectetur',
  //   image: '/assets/images/portfolio/product-2.jpg',
  // },
  // {
  //   id: 7,
  //   heading: 'Branding 2',
  //   content: 'Lorem ipsum, dolor sit amet consectetur',
  //   image: '/assets/images/portfolio/branding-2.jpg',
  // },
  // {
  //   id: 8,
  //   heading: 'Books 2',
  //   content: 'Lorem ipsum, dolor sit amet consectetur',
  //   image: '/assets/images/portfolio/books-2.jpg',
  // },
  // {
  //   id: 9,
  //   heading: 'App 3',
  //   content: 'Lorem ipsum, dolor sit amet consectetur',
  //   image: '/assets/images/portfolio/app-3.jpg',
  // },
  // {
  //   id: 10,
  //   heading: 'Product 3',
  //   content: 'Lorem ipsum, dolor sit amet consectetur',
  //   image: '/assets/images/portfolio/product-3.jpg',
  // },
  // {
  //   id: 11,
  //   heading: 'Branding 3',
  //   content: 'Lorem ipsum, dolor sit amet consectetur',
  //   image: '/assets/images/portfolio/branding-3.jpg',
  // },
  // {
  //   id: 12,
  //   heading: 'Books 3',
  //   content: 'Lorem ipsum, dolor sit amet consectetur',
  //   image: '/assets/images/portfolio/books-3.jpg',
  // },
];
